name: Java CI/CD Hexagonal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configura el entorno de Java (JDK 17 es el estándar actual)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven # Cachea las dependencias para que sea más rápido

      # 3. Da permisos de ejecución al Maven Wrapper
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      # 4. Compila y ejecuta tests (Limpia, compila y verifica)
      - name: Build and Test with Maven
        run: ./mvnw clean verify

      # 5. Opcional: Si quieres guardar el JAR resultante
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hexagonal-app
          path: target/*.jar